### ISSUE TITLE
Интеграция камеры с Алисой через Yandex Smart Home

### ISSUE THREAD

**Issue by mav10** [artgl/hass_rtkey#1]
Привет, классная статья на хабре и идея.

Решил вечером попробовать прикрутить это все быстренько и оно почти взлетело...
Я понимаю, что только начали и тут уже ишью на прилетело, но если будет возможность в будущем поправить - будет круто!

Что сделал:
- Установил HA  в Docker- контейнере
- Добавил вашу интеграцию
- В  HA картинка показывается (скриншот ниже)
- Добавил через `hacs`  *Yandex Smart Home*
- Подключил камеру в Алису - все добавилось. Но видео так и не прогружается (постоянный лоадер)

P.S. все настройки использовал по дефолту

![image](https://github.com/artgl/hass_rtkey/assets/20200808/96a529f8-01a5-4d92-a505-590ca13f4258)

<img width="375" alt="image" src="https://github.com/artgl/hass_rtkey/assets/20200808/b504b99b-06df-419c-a432-ba22f9595819">

<img width="375" alt="image" src="https://github.com/artgl/hass_rtkey/assets/20200808/ae5320eb-05bf-4ad9-9bfb-e3c27aa30fb2">

**Comment by artgl** [comment]
Проверил - у меня в приложении Яндекса проброшенная камера из интеграции работает.

Можно попробовать следующее:
1. Скачать последнюю версию интеграции из репозитория
2. Убедится что видео с камеры работатет в HA (не совсем понятно из описания видно ли в HA именно видео или просто меняющуюся раз в 2 секунды картинку)

**Comment by mav10** [comment]
Да с новой версией поток загрузился, спасибо
